CREATE DATABASE IF NOT EXISTS tasks_db;
use tasks_db;

CREATE TABLE IF NOT EXISTS tasks(
    id INT AUTO_INCREMENT PRIMARY KEY,
    task TEXT NOT NULL,
    completed BOOLEAN DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);